# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "창조의 블로그"
description: > # this means to ignore newlines until "email:"
   ヽ(´▽｀)ノ♪

email: ckdwh421@kookmin.ac.kr
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Lee changjo'
author: 'Lee changjo'
author_image: "/assets/images/author.jpg"

paginate:	5

url: ""      # the base hostname & protocol for your site
#baseurl: "https://creationeconomy.github.io/"
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/CreationEconomy
    desc:	my github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

comment:
  provider: "disqus"
  disqus:
    shortname:  "changjo"